export const Events = {
  LOGIN_MODAL_VISIBILITY_UPDATED: "LOGIN_MODAL_VISIBILITY_UPDATED",
  LOGIN_MODAL_REQUESTED: "LOGIN_MODAL_REQUESTED",
  LOGOUT_USER_REQUESTED: "LOGOUT_USER_REQUESTED",
  USER_LOGGED_OUT: "USER_LOGGED_OUT",
  USER_SUCCESSFULLY_AUTHENTICATED: "USER_SUCCESSFULLY_AUTHENTICATED",
  SESSION_STATUS_UPDATED: "SESSION_STATUS_UPDATED"
};
